apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: fed-export
  namespace: mesh1-system
spec:
  version: v2.1
  cluster:
    name: cluster1
    network: network1
  runtime:
    defaults:
      container:
        imageRegistry: quay.io/maistra
        imageTag: latest-2.1-qe
        imagePullPolicy: Always
    components:
      pilot:
        container:
          imageRegistry: registry.gitlab.com/dgrimm/istio
          imageTag: dgn
          imageName: pilot
          imagePullPolicy: Always
  addons:
    grafana:
      enabled: false
    kiali:
      enabled: false
    prometheus:
      enabled: false
  tracing:
    type: Jaeger
    sampling: 10000
  proxy:
    runtime:
      container:
        imageRegistry: registry.gitlab.com/dgrimm/istio
        imageTag: dgn
        imageName: registry.gitlab.com/dgrimm/istio/proxyv2:dgn
        imagePullPolicy: Always
    accessLogging:
      file:
        name: /dev/stdout
  techPreview:
    meshConfig:
      defaultConfig:
        holdApplicationUntilProxyStarts: false
        proxyMetadata:
          ISTIO_META_DNS_CAPTURE: "true"
          PROXY_XDS_VIA_AGENT: "true"
  gateways:
    additionalEgress:
      federation-egress:
        enabled: true
        requestedNetworkView:
        - network-mesh2
        routerMode: sni-dnat
        service:
          metadata:
            labels:
              federation.maistra.io/proxy: mesh2
          ports:
          - port: 15443
            name: tls
          - port: 8188
            name: http-discovery
        runtime:
          deployment:
            autoScaling:
              enabled: false
          container:
            # constrain resources for use in smaller environments
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits: {}
    additionalIngress:
      federation-ingress:
        enabled: true
        routerMode: sni-dnat
        service:
          type: LoadBalancer
          metadata:
            labels:
              federation.maistra.io/proxy: mesh2
          ports:
          - port: 15443
            name: tls
          - port: 8188
            name: https-discovery
        runtime:
          deployment:
            autoScaling:
              enabled: false
          container:
            # constrain resources for use in smaller environments
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits: {}
  security:
    trust:
      domain: mesh1.local
